# Generated by Django 2.0 on 2017-12-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_auto_20171223_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entree',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Projet'),
        ),
    ]
