# Generated by Django 2.1 on 2018-10-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_auto_20181028_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Information text', verbose_name='text')),
                ('creation_date', models.DateTimeField(editable=False, help_text='Date of creation of the information', verbose_name='creation date')),
                ('update_date', models.DateTimeField(editable=False, help_text='Date of last modification of the information text', verbose_name='update date')),
                ('codex', models.ForeignKey(help_text='Codex of the information', on_delete=django.db.models.deletion.CASCADE, related_name='information', to='projets.Codex')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='codex',
            field=models.ForeignKey(help_text='Codex of the page', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='projets.Codex', unique_for_date='date'),
        ),
    ]
